-- FR24 acquisition, recorded rather than merged.
--
-- fr24_staging_flight upserted one row per flight and moved a handful of *_seen_at stamps as
-- values changed. That answers "what does FR24 say now" and destroys "what did FR24 say before" —
-- the trigger held the old value and the new one in the same breath and kept only the new one.
-- Roughly 350 sweeps of transitions were lost that way between 10 Aug 16:37Z and this migration.
--
-- This table takes the opposite position: every field, every refresh, append-only, no merge. It is
-- the record of what we were told and when. Nothing derives, nothing overwrites, nothing is
-- reconciled here. Interpretation belongs downstream in `flight`; permanence belongs in
-- `flight_history`. This is the tape.
--
-- Measured volume before writing it: 105,909 rows in 12.59 hours, ~8.4k/hour, ~202k/day.

begin;

create table if not exists fr24_flight_raw (
  id            bigserial primary key,

  -- Provenance: which request produced this row. probe_uid is generated by the harvester so the
  -- request row and the flights it returned can be written independently, without a round trip to
  -- learn an id.
  observed_at   timestamptz not null default now(),
  probe_uid     uuid,
  source_airport text not null,
  page          int  not null,
  -- Which of FR24's two lists carried it. The same leg appears in DAM's departures and ALP's
  -- arrivals with different detail on each side; staging deduplicated that away and could not
  -- afterwards say which side had said what.
  direction     text not null check (direction in ('departure','arrival')),

  -- Identity, as filed. num is FR24's own choice of identifier and is sometimes the IATA number,
  -- sometimes the callsign, sometimes only a registration. Resolution happens downstream.
  fr24_id       text,
  num           text,
  callsign      text,
  airline_iata  text,
  airline_icao  text,
  airline_name  text,
  reg           text,
  hex           text,
  aircraft_code text,
  aircraft_text text,

  -- Endpoints. FR24 omits the observing airport's own code on one side of every entry.
  dep_iata      text,
  dep_icao      text,
  dep_name      text,
  arr_iata      text,
  arr_icao      text,
  arr_name      text,

  -- Times. Sent as unix seconds; held as timestamptz, which is the same instant and queryable.
  -- The literal integers remain in `raw` for anyone who wants to check.
  sched_dep     timestamptz,
  sched_arr     timestamptz,
  est_dep       timestamptz,
  est_arr       timestamptz,
  real_dep      timestamptz,
  real_arr      timestamptz,
  eta           timestamptz,
  src_updated   timestamptz,          -- time.other.updated: FR24's own idea of its freshness

  dep_terminal  text,
  dep_gate      text,
  arr_terminal  text,
  arr_gate      text,
  arr_baggage   text,

  -- Status is stored because FR24 said it, not because it is believed. Measured across 28 flights
  -- seen from both ends, the timestamps agreed and the status strings disagreed 27 times.
  status_text    text,
  status_generic text,
  status_type    text,
  status_icon    text,
  status_live    boolean,

  -- The local day of scheduled departure, which is how FR24 files departures and how the board
  -- buckets. Derived, and the one derivation allowed here, because it is the query key.
  flight_date   date,

  -- The entry verbatim. The guarantee that a field we did not think to extract is not lost.
  raw           jsonb not null
);

-- Per-flight chronology: the reason the table exists.
create index if not exists fr24_flight_raw_flight_idx
  on fr24_flight_raw (flight_date, num, observed_at desc);

-- Append-only and time-ordered, so BRIN indexes the retention scan at a fraction of a btree's
-- write cost and size.
create index if not exists fr24_flight_raw_observed_brin
  on fr24_flight_raw using brin (observed_at);

create index if not exists fr24_flight_raw_probe_idx
  on fr24_flight_raw (probe_uid);

comment on table fr24_flight_raw is
  'Append-only record of every FR24 schedule entry on every refresh. Never updated, never merged. Retention is short; flight_history is the permanent product.';


-- The probe table was never staging — it is the request log, and it outlives every table around
-- it. Naming it honestly stops it looking like scaffolding due for removal.
alter table if exists fr24_staging_probe rename to fr24_raw_probe;
alter table if exists fr24_raw_probe add column if not exists probe_uid uuid;
create index if not exists fr24_raw_probe_uid_idx on fr24_raw_probe (probe_uid);

comment on table fr24_raw_probe is
  'One row per FR24 request: what was asked, what came back, how long it took. Payload sampled, not kept. Permanent infrastructure, not staging.';


-- Staging proved acquisition works, proved the board contract is reachable from it, and proved
-- the two airports agree on timestamps. It has no further job, and keeping it would leave two
-- representations of the same flights with a standing question about which is true.
drop table if exists fr24_staging_flight;
drop function if exists fr24_staging_stamp();

commit;
